displayName=Barcrawl
author=Yenof, Ava
description=Food and drink collection log, basically.
tags=collection, log, clog, food, drink, barcrawl, extreme, challenge,
version=0.9
plugins=com.barcrawl.BarcrawlPlugin
build=standard